plugins {
    id "com.android.application"
}

android {
    namespace "com.jobinbasani.numbertowords"

    compileSdk 36

    defaultConfig {
        applicationId "com.jobinbasani.numbertowords"
        minSdk 16
        targetSdk 36
        versionCode 4
        versionName "2.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "androidx.appcompat:appcompat:1.5.1" // keep if you must support minSdk 16
}
